### ISSUE TITLE
How to install this ?

### ISSUE THREAD

**Issue by PatrickHonorez** [rawbytz/link-editor#1]
Hi, 
This looks interesting, but what does "install this in your script manager" mean ?
Sorry - I normally feel like an experienced user - but I can't see what that means.
Thanks

**Comment by rawbytz** [comment]
Sorry, I didn't go crazy with the README because I fully expect WorkFlowy to implement this functionality soon.  

You need to install a script manager extension (I use [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)) Once installed, clicking the link will install the script.  Once installed, you only need to reload any WorkFlowy tabs, and you should be good to go.
